export const INCOME_CATEGORIES = [
  "Salary",
  "Freelance",
  "Business",
  "Rental Income",
  "Dividend",
  "Interest",
  "Bonus",
  "Pension",
  "Capital Gain",
  "Gift",
  "Other Income",
];

export const EXPENSE_CATEGORIES = [
  "Food & Dining",
  "Transport",
  "Shopping",
  "Utilities & Bills",
  "Healthcare",
  "Entertainment",
  "EMI / Loan",
  "Education",
  "Personal Care",
  "Subscriptions",
  "Home & Rent",
  "Groceries",
  "Fuel",
  "Clothing",
  "Travel",
  "Eating Out",
  "Other Expense",
];

export const INVESTMENT_CATEGORIES = [
  "Stocks — NSE/BSE",
  "Stocks — US",
  "Mutual Fund — Equity",
  "Mutual Fund — Debt",
  "Mutual Fund — Hybrid",
  "Index Fund / ETF",
  "PPF",
  "EPF / PF",
  "NPS",
  "Fixed Deposit",
  "Recurring Deposit",
  "Bonds / Debentures",
  "Sovereign Gold Bond",
  "Gold / Silver Physical",
  "REIT / InvIT",
  "Real Estate",
  "Cryptocurrency",
  "ULIP",
  "Other Investment",
];

export const INSURANCE_CATEGORIES = [
  "Term Life Insurance",
  "LIC Endowment",
  "LIC Money Back",
  "LIC Jeevan Anand",
  "ULIP Insurance",
  "Whole Life Insurance",
  "Health Insurance — Individual",
  "Health Insurance — Family",
  "Critical Illness Cover",
  "Personal Accident",
  "Car Insurance",
  "Two-Wheeler Insurance",
  "Home / Property Insurance",
  "Travel Insurance",
  "PLI (Postal Life Insurance)",
  "Rural PLI",
  "PMJJBY",
  "PMSBY",
  "Marine Insurance",
  "Fire Insurance",
  "Other Insurance",
];

export const ALL_CATS = {
  income: INCOME_CATEGORIES,
  expense: EXPENSE_CATEGORIES,
  investment: INVESTMENT_CATEGORIES,
  insurance: INSURANCE_CATEGORIES,
};

export const VALID_TYPES = ["income", "expense", "investment", "insurance"];

export const CATEGORY_ICONS = {
  Salary: "💼",
  Freelance: "💻",
  Business: "🏢",
  "Rental Income": "🏘️",
  Dividend: "💹",
  Interest: "🏦",
  Bonus: "🎯",
  Pension: "👴",
  "Capital Gain": "📈",
  Gift: "🎁",
  "Other Income": "✨",
  "Food & Dining": "🍽️",
  Transport: "🚌",
  Shopping: "🛍️",
  "Utilities & Bills": "📄",
  Healthcare: "💊",
  Entertainment: "🎬",
  "EMI / Loan": "🏠",
  Education: "📚",
  "Personal Care": "💆",
  Subscriptions: "📱",
  "Home & Rent": "🏡",
  Groceries: "🛒",
  Fuel: "⛽",
  Clothing: "👗",
  Travel: "✈️",
  "Eating Out": "🍜",
  "Other Expense": "📦",
  "Stocks — NSE/BSE": "📉",
  "Stocks — US":"📉",
  "Mutual Fund — Equity": "📈",
  "Mutual Fund — Debt": "📊",
  "Mutual Fund — Hybrid": "⚖️",
  "Index Fund / ETF": "🗂️",
  PPF: "🏛️",
  "EPF / PF": "🏢",
  NPS: "🪙",
  "Fixed Deposit": "🔒",
  "Recurring Deposit": "🔄",
  "Bonds / Debentures": "📋",
  "Sovereign Gold Bond": "🥇",
  "Gold / Silver Physical": "🏅",
  "REIT / InvIT": "🏗️",
  "Real Estate": "🏠",
  Cryptocurrency: "₿",
  ULIP: "💎",
  "Other Investment": "🧩",
  "Term Life Insurance": "🛡️",
  "LIC Endowment": "🏛️",
  "LIC Money Back": "💰",
  "LIC Jeevan Anand": "🌟",
  "ULIP Insurance": "💎",
  "Whole Life Insurance": "♾️",
  "Health Insurance — Individual": "👤",
  "Health Insurance — Family": "👨‍👩‍👧",
  "Critical Illness Cover": "🏥",
  "Personal Accident": "🩹",
  "Car Insurance": "🚗",
  "Two-Wheeler Insurance": "🏍️",
  "Home / Property Insurance": "🏡",
  "Travel Insurance": "🌍",
  "PLI (Postal Life Insurance)": "📮",
  "Rural PLI": "🌾",
  PMJJBY: "📜",
  PMSBY: "🛟",
  "Marine Insurance": "⚓",
  "Fire Insurance": "🔥",
  "Other Insurance": "📑",
};

export const TYPE_META = {
  income: { color: "var(--income)", dim: "var(--income-dim)", label: "Income", icon: "📥", sign: "+" },
  expense: { color: "var(--expense)", dim: "var(--expense-dim)", label: "Expense", icon: "📤", sign: "-" },
  investment: { color: "var(--invest)", dim: "var(--invest-dim)", label: "Investment", icon: "📊", sign: "→" },
  insurance: { color: "var(--insure)", dim: "var(--insure-dim)", label: "Insurance", icon: "🛡️", sign: "→" },
};

export const PIE_COLORS = ["#C8A96E", "#E8C870", "#A07850", "#D4B896", "#F0DEB4", "#8A6840"];
export const INV_COLORS = ["#818CF8", "#A78BFA", "#C084FC", "#E879F9", "#F472B6", "#7DD3FC"];
export const INS_COLORS = ["#FB923C", "#F97316", "#FDBA74", "#FED7AA", "#FCA5A5", "#FCD34D"];
export const MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
